# Generated by Django 5.2.4 on 2025-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('marital_status', models.CharField(default='single', max_length=50)),
                ('password', models.CharField(default='Temp@1234', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
