# Generated by Django 5.2.4 on 2025-07-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_basicinfo_last_email_sync_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
