# Generated by Django 5.2.4 on 2025-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_financialreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='marital_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
